"""Description de la migration

Revision ID: 490fd76ac577
Revises: 
Create Date: 2025-02-23 14:38:37.098331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490fd76ac577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaissement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaissement', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
